In [1]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#reading the data into dataframe
dataframe=pd.read_csv("insurance_pre.csv")

In [3]:
dataframe.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [4]:
dataframe_processed=pd.get_dummies(dataframe, drop_first=True)

In [5]:
dataframe_processed.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400     False        True
1   18  33.770         1   1725.55230      True       False
2   28  33.000         3   4449.46200      True       False
3   33  22.705         0  21984.47061      True       False
4   32  28.880         0   3866.85520      True       False

In [6]:
dataframe_processed.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataframe_processed[['age', 'bmi', 'children', 'sex_male', 'smoker_yes' ]]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0     False        True
1   18  33.770         1      True       False
2   28  33.000         3      True       False
3   33  22.705         0      True       False
4   32  28.880         0      True       False

In [8]:
dependent=dataframe_processed[[ 'charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [9]:
# #split into training set and test set
# from sklearn.model_selection import train_test_split
# X_train,X_test,y_train,y_test= train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [10]:
# from sklearn.preprocessing import StandardScaler
# sc=StandardScaler()
# X_train=sc.fit_transform(X_train)
# X_test=sc.transform(X_test)

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = { 'kernel' : ['rbf','poly','sigmoid','linear'],
                'C' : [10,100,1000,2000,3000],
                'gamma' : ['auto','scale']
              }

In [12]:
grid=GridSearchCV(SVR(), param_grid, refit=True, verbose = 3, n_jobs = -1)

In [ ]:
#grid.fit(X_train,y_train)
grid.fit(independent,dependent)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

In [ ]:
#print best parameter after tuning
print(grid.best_params_)

In [ ]:
re=grid.cv_results_

In [ ]:
print("The  r_Score value for the best parameter {}".format(grid.best_params_))

In [ ]:
#re
table=pd.DataFrame.from_dict(re)

In [ ]:
table

In [ ]:
# #'age', 'bmi', 'children',  'sex_male', 'smoker_yes
age_input=float(input("Age:"))
bmi_input=float(input("Bmi: "))
children_input=float(input("Number of Children: "))
sex_input=int(input("Male 1 or Female 0: "))
smoker_input=int(input("Smoker 1 or Non Smoker 0: "))

In [ ]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_input,smoker_input]])

In [ ]:
print("Future_Preduction={}".format(Future_Prediction))