In [1]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#reading the data into dataframe
dataframe=pd.read_csv("insurance_pre.csv")

In [3]:
dataframe.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [4]:
dataframe_processed=pd.get_dummies(dataframe, drop_first=True)

In [5]:
dataframe_processed.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400     False        True
1   18  33.770         1   1725.55230      True       False
2   28  33.000         3   4449.46200      True       False
3   33  22.705         0  21984.47061      True       False
4   32  28.880         0   3866.85520      True       False

In [6]:
dataframe_processed.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataframe_processed[['age', 'bmi', 'children', 'sex_male', 'smoker_yes' ]]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0     False        True
1   18  33.770         1      True       False
2   28  33.000         3      True       False
3   33  22.705         0      True       False
4   32  28.880         0      True       False

In [8]:
dependent=dataframe_processed[[ 'charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [9]:
# #split into training set and test set
# from sklearn.model_selection import train_test_split
# X_train,X_test,y_train,y_test= train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [10]:
# from sklearn.preprocessing import StandardScaler
# sc=StandardScaler()
# X_train=sc.fit_transform(X_train)
# X_test=sc.transform(X_test)

In [11]:
from sklearn.model_selection import GridSearchCV
#from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
param_grid = { 'criterion' : ['squared_error','absolute_error','friedman_mse','poisson'],
                'max_features' : ['auto','sqrt','log2'],
                'splitter' : ['best','random']
              }

In [12]:
grid=GridSearchCV(DecisionTreeRegressor(), param_grid, refit=True, verbose = 3, n_jobs = -1)

In [13]:
#grid.fit(X_train,y_train)
grid.fit(independent,dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
23 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
17 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.67800888 0.62525698 0.61644533 0.66138939
        nan        nan 0.69805816 0.63465703 0.63376793 0.6380791
        nan        nan 0.68222623 0.64653387 0.70995556 0.62371397
        nan        nan 0.62069099 0.63102362 0.69439758 0.62859351]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [14]:
#print best parameter after tuning
print(grid.best_params_)

{'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'}

In [15]:
re=grid.cv_results_

In [16]:
print("The  r_Score value for the best parameter {}".format(grid.best_params_))

The  r_Score value for the best parameter {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'}

In [17]:
#re
table=pd.DataFrame.from_dict(re)

In [18]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.014729,0.006730,0.000000,0.000000,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.013679,0.003183,0.000000,0.000000,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.033621,0.013558,0.017049,0.009609,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.743677,0.680297,0.736567,0.679854,0.549650,0.678009,0.069607,5
3,0.038854,0.018463,0.024565,0.008266,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.671848,0.404912,0.663550,0.661911,0.724064,0.625257,0.112513,13
4,0.034425,0.016310,0.016848,0.009330,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.647694,0.510088,0.544172,0.684319,0.695954,0.616445,0.075419,16
5,0.037230,0.013663,0.022226,0.006754,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.677197,0.639430,0.670224,0.662677,0.657419,0.661389,0.012865,6
6,0.009525,0.004312,0.000000,0.000000,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.010529,0.005730,0.000000,0.000000,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.146155,0.014768,0.018084,0.002642,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.667517,0.627537,0.735508,0.723170,0.736559,0.698058,0.043408,2
9,0.111606,0.010657,0.027821,0.003733,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.631929,0.603648,0.650811,0.623101,0.663798,0.634657,0.021037,9
10,0.144971,0.019570,0.029051,0.003764,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.657446,0.626884,0.633449,0.529383,0.721678,0.633768,0.062020,10
11,0.119116,0.023785,0.022127,0.009233,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.698503,0.622455,0.584291,0.650448,0.634699,0.638079,0.037290,8
12,0.009213,0.004068,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.009632,0.001645,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.035022,0.008701,0.021062,0.007101,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.725786,0.659276,0.602786,0.698623,0.724660,0.682226,0.046485,4
15,0.036989,0.006376,0.023165,0.008345,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.636514,0.554116,0.648261,0.630489,0.763289,0.646534,0.067132,7
16,0.055143,0.005127,0.024069,0.009086,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.776148,0.597015,0.697544,0.720194,0.758877,0.709956,0.062911,1
17,0.035175,0.013600,0.025492,0.005919,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.618364,0.509336,0.727465,0.676552,0.586853,0.623714,0.074868,14
18,0.009713,0.003887,0.000000,0.000000,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.006535,0.002143,0.000000,0.000000,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.049494,0.004171,0.025077,0.001918,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.641583,0.378301,0.753591,0.701091,0.628888,0.620691,0.129138,15
21,0.037279,0.005103,0.021638,0.004685,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.688566,0.511333,0.690570,0.664935,0.599714,0.631024,0.068283,11
22,0.039999,0.009157,0.017980,0.005935,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.717788,0.569445,0.729493,0.728921,0.726340,0.694398,0.062616,3
23,0.030600,0.006808,0.013475,0.003428,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.583338,0.554456,0.673044,0.619066,0.713064,0.628594,0.057873,12

In [19]:
# #'age', 'bmi', 'children',  'sex_male', 'smoker_yes
age_input=float(input("Age:"))
bmi_input=float(input("Bmi: "))
children_input=float(input("Number of Children: "))
sex_input=int(input("Male 1 or Female 0: "))
smoker_input=int(input("Smoker 1 or Non Smoker 0: "))

Age: 32
Bmi:  43
Number of Children:  2
Male 1 or Female 0:  1
Smoker 1 or Non Smoker 0:  0

In [20]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_input,smoker_input]])

C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

In [21]:
print("Future_Preduction={}".format(Future_Prediction))

Future_Preduction=[4686.3887]