In [1]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#reading the data into dataframe
dataframe=pd.read_csv("insurance_pre.csv")

In [3]:
dataframe.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [4]:
dataframe_processed=pd.get_dummies(dataframe, drop_first=True)

In [5]:
dataframe_processed.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400     False        True
1   18  33.770         1   1725.55230      True       False
2   28  33.000         3   4449.46200      True       False
3   33  22.705         0  21984.47061      True       False
4   32  28.880         0   3866.85520      True       False

In [6]:
dataframe_processed.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataframe_processed[['age', 'bmi', 'children', 'sex_male', 'smoker_yes' ]]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0     False        True
1   18  33.770         1      True       False
2   28  33.000         3      True       False
3   33  22.705         0      True       False
4   32  28.880         0      True       False

In [8]:
dependent=dataframe_processed[[ 'charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [9]:
# #split into training set and test set
# from sklearn.model_selection import train_test_split
# X_train,X_test,y_train,y_test= train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [10]:
# from sklearn.preprocessing import StandardScaler
# sc=StandardScaler()
# X_train=sc.fit_transform(X_train)
# X_test=sc.transform(X_test)

In [11]:
from sklearn.model_selection import GridSearchCV
#from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
param_grid = { 'criterion' : ['squared_error','absolute_error','friedman_mse','poisson'],
                'max_features' : ['auto','sqrt','log2'],
                'n_estimators' : [10,100]
              }

In [12]:
grid=GridSearchCV(RandomForestRegressor(), param_grid, refit=True, verbose = 3, n_jobs = -1)

In [13]:
#grid.fit(X_train,y_train)
grid.fit(independent,dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
8 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
32 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.81245229 0.83283335 0.80906436 0.8339746
        nan        nan 0.82330102 0.83302055 0.81972274 0.83330768
        nan        nan 0.81921574 0.8339841  0.81956178 0.8324689
        nan        nan 0.82094087 0.83505376 0.82065737 0.83373807]
  warnings.warn(
C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [14]:
#print best parameter after tuning
print(grid.best_params_)

{'criterion': 'poisson', 'max_features': 'sqrt', 'n_estimators': 100}

In [15]:
re=grid.cv_results_

In [16]:
print("The  r_Score value for the best parameter {}".format(grid.best_params_))

The  r_Score value for the best parameter {'criterion': 'poisson', 'max_features': 'sqrt', 'n_estimators': 100}

In [17]:
#re
table=pd.DataFrame.from_dict(re)

In [18]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.022945,0.017355,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.028949,0.007832,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.446597,0.107105,0.055096,0.026200,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.844338,0.744938,0.828228,0.814720,0.830038,0.812452,0.035037,15
3,2.814714,0.127507,0.155213,0.030954,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.859130,0.776471,0.861499,0.826950,0.840117,0.832833,0.030912,7
4,0.382387,0.074843,0.050039,0.013087,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.834033,0.752050,0.835848,0.805249,0.818142,0.809064,0.030622,16
5,2.402506,0.584158,0.136010,0.049559,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.858065,0.781661,0.858224,0.833158,0.838766,0.833975,0.028031,3
6,0.019788,0.028850,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.055440,0.090382,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,2.074740,0.434512,0.107179,0.089313,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.849903,0.768187,0.846789,0.825414,0.826211,0.823301,0.029359,9
9,6.199959,0.181076,0.046176,0.003736,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.856160,0.779957,0.853408,0.828106,0.847472,0.833021,0.028283,6
10,0.920554,0.043214,0.041541,0.007176,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.830143,0.766022,0.837561,0.821715,0.843173,0.819723,0.027801,12
11,5.680405,0.133472,0.041464,0.001970,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.853107,0.784656,0.858223,0.826697,0.843856,0.833308,0.026589,5
12,0.010457,0.004439,0.000000,0.000000,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.009236,0.003555,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.255889,0.031510,0.037900,0.010665,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.841040,0.747367,0.862158,0.815823,0.829690,0.819216,0.038997,14
15,2.376033,0.067739,0.137862,0.011382,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.857528,0.780539,0.863289,0.829053,0.839510,0.833984,0.029409,2
16,0.285315,0.015033,0.045392,0.007643,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.841599,0.769369,0.831758,0.821070,0.834013,0.819562,0.025942,13
17,2.340715,0.049769,0.107683,0.008843,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.858942,0.778531,0.857558,0.826044,0.841271,0.832469,0.029524,8
18,0.011740,0.002732,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.013652,0.002687,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.282737,0.021451,0.040796,0.006468,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.852194,0.761174,0.858814,0.809623,0.822899,0.820941,0.034972,10
21,1.865911,0.037059,0.079601,0.008491,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.859114,0.781940,0.861583,0.829222,0.843410,0.835054,0.029009,1
22,0.298336,0.015030,0.041098,0.009859,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.849903,0.749314,0.843761,0.824758,0.835550,0.820657,0.036654,11
23,1.667794,0.024246,0.050135,0.002693,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.858338,0.776643,0.860706,0.831333,0.841670,0.833738,0.030532,4

In [19]:
# #'age', 'bmi', 'children',  'sex_male', 'smoker_yes
age_input=float(input("Age:"))
bmi_input=float(input("Bmi: "))
children_input=float(input("Number of Children: "))
sex_input=int(input("Male 1 or Female 0: "))
smoker_input=int(input("Smoker 1 or Non Smoker 0: "))

Age: 32
Bmi:  43
Number of Children:  2
Male 1 or Female 0:  1
Smoker 1 or Non Smoker 0:  0

In [20]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_input,smoker_input]])

C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [21]:
print("Future_Preduction={}".format(Future_Prediction))

Future_Preduction=[4938.9645011]