In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
#loading data
dataframe=pd.read_csv("insurance_pre.csv")

In [3]:
dataframe.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [4]:
dataframe.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

In [5]:
# Convert Categorical to Dummy Variables
dataframe_processed = pd.get_dummies(dataframe, columns=['sex', 'smoker'], drop_first=True)

In [6]:
dataframe_processed.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400     False        True
1   18  33.770         1   1725.55230      True       False
2   28  33.000         3   4449.46200      True       False
3   33  22.705         0  21984.47061      True       False
4   32  28.880         0   3866.85520      True       False

In [7]:
dataframe_processed.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [8]:
#independent=dataframe_processed[['age', 'bmi', 'children',  'sex_male', 'smoker_yes']]

In [9]:
# 2. Define X and y which is independent and dependent
independent = dataframe_processed.drop('charges', axis=1) #X
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0     False        True
1   18  33.770         1      True       False
2   28  33.000         3      True       False
3   33  22.705         0      True       False
4   32  28.880         0      True       False

In [10]:
dependent=dataframe_processed[['charges']] #Y
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [11]:
#from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.3, random_state=0)

### from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

In [13]:
weight=regressor.coef_
weight

array([[  257.8006705 ,   321.06004271,   469.58113407,   -41.74825718,
        23418.6671912 ]])

In [14]:
bias=regressor.intercept_
bias

array([-12057.244846])

In [15]:
y_predict=regressor.predict(X_test)

In [16]:
from sklearn.metrics import r2_score
rscore=r2_score(y_predict,y_test)
rscore

0.7100923694262503

In [17]:
import pickle
pickle.dump(regressor,open("Wk3_Asgn_mliear_001.sav","wb"))

In [18]:
# Deploying saved model 
loaded_model=pickle.load(open("Wk3_Asgn_mliear_001.sav","rb"))

In [19]:
#'age', 'bmi', 'children',  'sex_male', 'smoker_yes
age_input=float(input("Age:"))
bmi_input=float(input("Bmi: "))
children_input=float(input("Number of Children: "))
sex_input=int(input("Male 1 or Female 0: "))
smoker_input=int(input("Smoker 1 or Non Smoker 0: "))

Age: 23
Bmi:  33.7
Number of Children:  3
Male 1 or Female 0:  1
Smoker 1 or Non Smoker 0:  0

In [20]:
result=loaded_model.predict([[age_input,bmi_input,children_input,sex_input,smoker_input]])

C:\Users\Muthukrishnan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [21]:
result

array([[6058.88915965]])